"""
Rosalind - AH - Fibonacci Numbers

The Fibonacci numbers 0,1,1,2,3,5,8,13,21,34,…
 are generated by the following simple rule
Fn = [  Fn−1+Fn−2,   n>1,
        1,            n=1,
        0,            n=0.  ]

Given: A positive integer n≤25.
Return: The value of Fn.
"""


# Method 1: normal for loop
def Fib_Loop(num):
    old = 1
    new = 1
    for itr in range(num-1):
        tmpVal = new
        new = old
        old = old + tmpVal
    return new


# Method 2: a more pythonic solution to this problem
def Fib_Pythonic(num):
    old, new = 1, 1
    for itr in range(num-1):
        new, old = old, old + new
    return new

# Method 3:
